export enum SessionDay { 
  MONDAY = 'SEGUNDA-FEIRA',
  TUESDAY = 'TERÇA-FEIRA',
  WEDNESDAY = 'QUARTA-FEIRA',
  THURSDAY = 'QUINTA-FEIRA',
  FRIDAY = 'SEXTA-FEIRA',
  SATURDAY = 'SÁBADO',
  SUNDAY = 'DOMINGO'
}